<?php
/**
 * WooCommerce Conflict Doctor — MU-Plugin Loader
 *
 * SOURCE FILE: woocommerce-conflict-doctor/mu-plugin/wcd-loader.php
 * This file is copied to wp-content/mu-plugins/wcd-loader.php on first wizard run.
 * Edit the source in the plugin, not the copy in mu-plugins/.
 *
 * Hooks option_active_plugins, stylesheet, and template to scope plugin/theme
 * disabling to a single admin session identified by a per-user cookie.
 * Live visitor traffic is never affected.
 *
 * Uses define() constants and local variables only — this runs before any
 * plugin class (including WCD_Troubleshoot_Mode) is available.
 *
 * The cookie name and session prefix below MUST match the values in wcd-constants.php:
 *   WCD_COOKIE_NAME    = 'wcd_troubleshoot_' . substr( md5( ABSPATH ), 0, 8 )
 *   WCD_SESSION_PREFIX = 'wcd_session_'
 *
 * option_active_plugins is a stable WordPress core filter since WP 2.9.
 * It is NOT a Health Check invention. mu-plugins/ loads before regular plugins,
 * which is why this filter can intercept the active plugin list.
 */

defined( 'ABSPATH' ) || exit;

// Computed identically to WCD_COOKIE_NAME in wcd-constants.php.
$_wcd_cookie_name = 'wcd_troubleshoot_' . substr( md5( ABSPATH ), 0, 8 );

if ( ! isset( $_COOKIE[ $_wcd_cookie_name ] ) ) {
	return;
}

$_wcd_raw_token = $_COOKIE[ $_wcd_cookie_name ];

// Only alphanumeric + hyphens are valid token characters (generated by bin2hex).
if ( ! preg_match( '/^[a-f0-9]{32}$/', $_wcd_raw_token ) ) {
	return;
}

$_wcd_token      = $_wcd_raw_token;
$_wcd_option_key = 'wcd_session_' . $_wcd_token;
$_wcd_session    = get_option( $_wcd_option_key );

if ( ! is_array( $_wcd_session ) ) {
	return;
}

// Validate TTL — expired session = pass through, no filtering.
if ( empty( $_wcd_session['expires_at'] ) || time() > (int) $_wcd_session['expires_at'] ) {
	return;
}

// Validate token matches what's stored in the session (prevents option-key spoofing).
if ( empty( $_wcd_session['token'] ) || ! hash_equals( (string) $_wcd_session['token'], $_wcd_token ) ) {
	return;
}

$_wcd_disabled = isset( $_wcd_session['disabled'] ) ? (array) $_wcd_session['disabled'] : array();
$_wcd_theme    = isset( $_wcd_session['theme'] ) ? (string) $_wcd_session['theme'] : '';

// Filter active plugins — remove disabled set for this session only.
// Runs when WordPress reads get_option('active_plugins') in wp-settings.php.
add_filter(
	'option_active_plugins',
	static function( $plugins ) use ( $_wcd_disabled ) {
		if ( empty( $_wcd_disabled ) ) {
			return $plugins;
		}
		return array_values( array_diff( (array) $plugins, $_wcd_disabled ) );
	}
);

// Override theme if the merchant chose a safe test theme.
if ( ! empty( $_wcd_theme ) ) {
	add_filter( 'option_stylesheet', static function() use ( $_wcd_theme ) { return $_wcd_theme; } );
	add_filter( 'option_template',   static function() use ( $_wcd_theme ) { return $_wcd_theme; } );
}

unset( $_wcd_cookie_name, $_wcd_raw_token, $_wcd_token, $_wcd_option_key,
	$_wcd_session, $_wcd_disabled, $_wcd_theme );
